export const BASE_CATALOG = {
  "Audi": ["A3", "A4", "Q3", "Q5", "A5", "Q8"],
  "BMW": ["118i", "320i", "X1", "X3", "X5", "M3"],
  "BYD": ["Dolphin", "Yuan Pro", "Yuan Plus", "Seal", "Song Plus"],
  "Chevrolet": ["Onix", "Onix Plus", "Tracker", "Cruze", "S10", "Spin"],
  "Citroën": ["C3", "C4 Cactus", "Aircross", "Jumpy"],
  "Fiat": ["Argo", "Cronos", "Toro", "Pulse", "Fastback", "Strada", "Mobi"],
  "Ford": ["Ka", "EcoSport", "Ranger", "Territory", "Bronco Sport"],
  "Honda": ["City", "Civic", "HR-V", "WR-V", "Fit"],
  "Hyundai": ["HB20", "Creta", "Tucson", "Santa Fe", "ix35"],
  "Jeep": ["Renegade", "Compass", "Commander", "Gladiator"],
  "Mercedes-Benz": ["A200", "C180", "C200", "GLA 200", "GLC 220d"],
  "Mitsubishi": ["L200 Triton", "Eclipse Cross", "Pajero Sport", "ASX"],
  "Nissan": ["Kicks", "Versa", "Sentra", "Frontier"],
  "Peugeot": ["208", "2008", "3008", "Partner"],
  "Porsche": ["Macan", "Cayenne", "911", "Panamera"],
  "Ram": ["Rampage", "1500", "2500"],
  "Renault": ["Kwid", "Sandero", "Logan", "Duster", "Oroch"],
  "Toyota": ["Corolla", "Corolla Cross", "Hilux", "SW4", "Yaris"],
  "Volkswagen": ["Gol", "Polo", "Virtus", "T-Cross", "Nivus", "Amarok"]
};

export const OPTIONALS = [
  "Ar-condicionado",
  "Direção elétrica",
  "Vidros elétricos",
  "Travas elétricas",
  "Central multimídia",
  "Câmera de ré",
  "Sensor de estacionamento",
  "Airbags",
  "Freios ABS",
  "Controle de estabilidade",
  "Piloto automático",
  "Banco de couro",
  "Rodas de liga leve",
  "Teto solar",
  "Chave presencial",
  "Partida por botão",
  "Manual e chave reserva",
  "Laudo cautelar aprovado",
  "IPVA pago",
  "Revisado"
];

export const FUELS = ["Flex", "Gasolina", "Diesel", "Etanol", "Híbrido", "Elétrico"];
export const TRANSMISSIONS = ["Manual", "Automático", "CVT", "Automatizado"];
export const COLORS = ["Branco", "Preto", "Prata", "Cinza", "Vermelho", "Azul", "Verde", "Marrom", "Bege"];
export const BODY_TYPES = ["Hatch", "Sedan", "SUV", "Picape", "Cupê", "Van", "Utilitário", "Esportivo"];

export const DEMO_VEHICLES = [
  {
    id: crypto.randomUUID(),
    status: "active",
    featured: true,
    brand: "Toyota",
    model: "Corolla",
    version: "Altis Hybrid Premium",
    yearModel: 2023,
    yearFabrication: 2022,
    price: 182900,
    priceDiscount: 176900,
    km: 18750,
    fuel: "Híbrido",
    transmission: "CVT",
    color: "Prata",
    bodyType: "Sedan",
    doors: 4,
    plateFinal: "7",
    city: "Cuiabá - MT",
    description: "Sedan confortável, econômico e muito procurado. Excelente para quem quer confiabilidade e baixo custo de uso.",
    optionals: ["Ar-condicionado", "Direção elétrica", "Central multimídia", "Câmera de ré", "Airbags", "Freios ABS", "Controle de estabilidade", "Manual e chave reserva", "Laudo cautelar aprovado"],
    image: "images/car.jpeg",
    createdAt: new Date().toISOString()
  },
  {
    id: crypto.randomUUID(),
    status: "active",
    featured: false,
    brand: "Volkswagen",
    model: "Nivus",
    version: "Highline 200 TSI",
    yearModel: 2024,
    yearFabrication: 2023,
    price: 137900,
    priceDiscount: null,
    km: 8900,
    fuel: "Flex",
    transmission: "Automático",
    color: "Azul",
    bodyType: "SUV",
    doors: 4,
    plateFinal: "2",
    city: "Cuiabá - MT",
    description: "SUV urbano com excelente aceitação de mercado, painel digital e bom pacote de conectividade.",
    optionals: ["Ar-condicionado", "Direção elétrica", "Vidros elétricos", "Central multimídia", "Câmera de ré", "Sensor de estacionamento", "Piloto automático", "Rodas de liga leve"],
    image: "images/car.avif",
    createdAt: new Date().toISOString()
  },
  {
    id: crypto.randomUUID(),
    status: "inactive",
    featured: false,
    brand: "Chevrolet",
    model: "Onix",
    version: "Premier 1.0 Turbo",
    yearModel: 2022,
    yearFabrication: 2021,
    price: 88900,
    priceDiscount: 84900,
    km: 31200,
    fuel: "Flex",
    transmission: "Automático",
    color: "Branco",
    bodyType: "Hatch",
    doors: 4,
    plateFinal: "9",
    city: "Várzea Grande - MT",
    description: "Compacto completo, econômico e de giro rápido. Ideal para ticket de entrada.",
    optionals: ["Ar-condicionado", "Direção elétrica", "Vidros elétricos", "Travas elétricas", "Central multimídia", "Airbags", "Freios ABS"],
    image: "images/car.jpeg",
    createdAt: new Date().toISOString()
  }
];
